version: 2

run:
  timeout: 3m
  tests: true
  build-tags:
    - integration

linters:
  # Use default linters but include integration tests
  disable-all: false

issues:
  # Exclude gosec from test files (expected test patterns)
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
